### ISSUE TITLE
Broken snapshot deployment build: Error while generating Javadoc

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jsonp#216] opened 2020-01-09 11:09 UTC
Jenkins snapshot build fails when runing
```
mvn -U -C -B -Psnapshots,oss-release clean install deploy
```
Cause seems to be an error in javadoc:
```
[INFO] JSON-P Default Provider ............................ FAILURE [  7.210 s]
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project jakarta.json: MavenReportException: Error while generating Javadoc: /home/jenkins/agent/workspace/jsonp-master-build/impl/target/apidocs/src/org.glassfish.java.json -> [Help 1]
```
https://ci.eclipse.org/jsonp/job/jsonp-master-build/28/console
Please fix this ASAP.

**Comment by m0mus** [comment] 2020-01-09 13:53
@Tomas-Kraus Please fix it.

**Comment by jonnes-nascimento** [comment] 2020-04-15 16:18
Hi guys!
I'm trying to help with this issue but I'm getting an error that I can't deal with.

```
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:jakarta.json:bundle:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:jsonp-jaxrs:bundle:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:jsonp-jaxrs-1x:bundle:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:customprovider:war:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:defaultprovider:war:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:providers:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:jsondemos-jaxrs:war:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:jsondemos-twitter:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:jsondemos-facebook:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:jsondemos-jsonpointer:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:jsondemos-servlet:war:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish.jsonp:demos:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:json-ri-bundle:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:json-bundles:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.glassfish:json:pom:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ org.eclipse.ee4j:project:1.0.6, /Users/jonnes/.m2/repository/org/eclipse/ee4j/project/1.0.6/project-1.0.6.pom, line 164, column 29
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Inspecting build with total of 15 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 15 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[WARNING] The project org.glassfish:json:pom:2.0.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Jakarta JSON Processing                                            [pom]
[INFO] JSON-P Default Provider                                         [bundle]
[INFO] Jakarta JSON Processing Media for Jakarta RESTful Web Services  [bundle]
[INFO] Jakarta JSON Processing Media for JAX-RS 1.1                    [bundle]
[INFO] providers                                                          [pom]
[INFO] customprovider                                                     [war]
[INFO] defaultprovider                                                    [war]
[INFO] demos                                                              [pom]
[INFO] jsondemos-jaxrs                                                    [war]
[INFO] jsondemos-twitter                                                  [jar]
[INFO] jsondemos-facebook                                                 [jar]
[INFO] jsondemos-jsonpointer                                              [jar]
[INFO] jsondemos-servlet                                                  [war]
[INFO] Jakarta JSON Processing bundles                                    [pom]
[INFO] RI Distribution zip bundle                                         [pom]
[INFO]
[INFO] -------------------------< org.glassfish:json >-------------------------
[INFO] Building Jakarta JSON Processing 2.0.0-SNAPSHOT                   [1/15]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/maven-metadata.xml
[INFO] Downloading from sonatype-nexus-snapshots: https://jakarta.oss.sonatype.org/content/repositories/snapshots/org/apache/maven/plugins/maven-enforcer-plugin/maven-metadata.xml
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/maven-metadata.xml (882 B at 303 B/s)
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ json ---
[INFO] Deleting /Users/jonnes/projects/jsonp/target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-maven) @ json ---
[INFO]
[INFO] --- directory-maven-plugin:0.3.1:highest-basedir (find-project-root) @ json ---
[INFO] Highest basedir set to: /Users/jonnes/projects/jsonp
[INFO]
[INFO] --- build-helper-maven-plugin:3.0.0:add-resource (add-legal-resource) @ json ---
[INFO]
[INFO] --- maven-javadoc-plugin:3.0.1:jar (attach-javadocs) @ json ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO]
[INFO] --- glassfish-copyright-maven-plugin:2.3:check (default) @ json ---
[INFO]
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ json ---
[INFO]
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ json ---
gpg: Sorry, no terminal at all requested - can't get input
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Jakarta JSON Processing 2.0.0-SNAPSHOT:
[INFO]
[INFO] Jakarta JSON Processing ............................ FAILURE [  6.556 s]
[INFO] JSON-P Default Provider ............................ SKIPPED
[INFO] Jakarta JSON Processing Media for Jakarta RESTful Web Services SKIPPED
[INFO] Jakarta JSON Processing Media for JAX-RS 1.1 ....... SKIPPED
[INFO] providers .......................................... SKIPPED
[INFO] customprovider ..................................... SKIPPED
[INFO] defaultprovider .................................... SKIPPED
[INFO] demos .............................................. SKIPPED
[INFO] jsondemos-jaxrs .................................... SKIPPED
[INFO] jsondemos-twitter .................................. SKIPPED
[INFO] jsondemos-facebook ................................. SKIPPED
[INFO] jsondemos-jsonpointer .............................. SKIPPED
[INFO] jsondemos-servlet .................................. SKIPPED
[INFO] Jakarta JSON Processing bundles .................... SKIPPED
[INFO] RI Distribution zip bundle ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.275 s
[INFO] Finished at: 2020-04-15T12:57:54-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project json: Exit code: 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```


I guess the issue is:

`gpg: Sorry, no terminal at all requested - can't get input`

I've just cloned the repository and did:

`mvn -U -C -B -Psnapshots,oss-release clean install deploy`

What's wrong? 
Help please!

**Comment by lukasj** [comment] 2020-07-16 16:04
should be fixed, reopen if not. Thx

**Closed by lukasj** 2020-07-16 16:04 UTC
Labels: Priority: Critical
